### ISSUE TITLE
Починить видео плеер на tvOS

### ISSUE THREAD

**Issue by flaksp** [midori-no-me/ichime#31]
На реальном девайсе видео работает, но нет сабов. Также есть баги с Picture-in-Picture: в пип переходит, но когда пип разворачиваешь на фулл скрин, то видео пропадает.

В симуляторе наоборот: видео не проигрывается, но если его поперематывать, то видно, что сабы рендерятся.

**Comment by dimensi** [comment]
починили, проблема была в способе загрузки сабов
