### ISSUE TITLE
Редизайн кнопки "Добавить в список"

### ISSUE THREAD

**Issue by flaksp** [midori-no-me/ichime#32]
Кнопка "Добавить в список" сейчас реализована через элемент `Menu`. Из-за этого есть проблемы с версткой, так как к `Menu` не применяются стили от кнопок, поэтому эта кнопка выглядит всрато рядом с кнопкой "Смотреть" (по крайней мере на tvOS).

Нужно переверстать это с помощью элемента `Button`:

- В виде лейбла кнопки должен отображаться текущий статус в списке.
- При нажатии по кнопке:
  - Если тайтла еще нет в моем списке, добавить его в список "Смотрю".
  - Если есть в списке, открывать такую же модалку как на экране "Мой список". Эту модалку следует переиспользовать.
- У кнопки на tvOS нужно задать `.buttonStyle(.card)` (и добавить `.padding()` по аналогии с кнопкой "Смотреть"), а на остальных платформах — `.buttonStyle(.bordered)`.

Такой редизайн позволит нам сделать кнопку симпатичной, а также позволит гибко управлять списком прямо с экрана сериала.

**Comment by dimensi** [comment]
Не запланировано ли? Потому что статус смотрю автоматом проставится если человек хоть 1 серию посмотрит
