### ISSUE TITLE
Поддержать "Моменты"

### ISSUE THREAD

**Issue by flaksp** [midori-no-me/ichime#40]
Только просмотр.

**Comment by dimensi** [comment]
А что именно? Добавить апи для этого или ещё экран сверстать?

**Comment by dimensi** [comment]
> думаю экрана момента не будет у нас
> название момента и сериала можно будет в плеер запихнуть
> а в контекстное меню можно будет запихнуть все остальное: поделиться, открыть сериал, открыть серию и тд
